# Generated by Django 3.2.16 on 2023-09-12 13:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0006_auto_20230912_1114'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='follow',
            name='subscriber',
        ),
        migrations.AddConstraint(
            model_name='follow',
            constraint=models.UniqueConstraint(fields=('user', 'following'), name='unique_user_following'),
        ),
    ]
